// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHs8Z4EhOUEcn1fr1KpNosGnISx_faY94',
    appId: '1:228705649518:web:d50ca1db26220fbe78377f',
    messagingSenderId: '228705649518',
    projectId: 'prakflutterfirebase-43945',
    authDomain: 'prakflutterfirebase-43945.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-43945.appspot.com',
    measurementId: 'G-4GG1FJMTPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcX2LANLmqBhLrAzCLRRp9xBR3nGmwYMc',
    appId: '1:228705649518:android:82f721a096c6f93078377f',
    messagingSenderId: '228705649518',
    projectId: 'prakflutterfirebase-43945',
    storageBucket: 'prakflutterfirebase-43945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEJ0NO-FECQNRe3u00EraLzS2dsR5t6A',
    appId: '1:228705649518:ios:ab613add24c9991078377f',
    messagingSenderId: '228705649518',
    projectId: 'prakflutterfirebase-43945',
    storageBucket: 'prakflutterfirebase-43945.appspot.com',
    iosBundleId: 'com.example.pertemuan09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGEJ0NO-FECQNRe3u00EraLzS2dsR5t6A',
    appId: '1:228705649518:ios:ab613add24c9991078377f',
    messagingSenderId: '228705649518',
    projectId: 'prakflutterfirebase-43945',
    storageBucket: 'prakflutterfirebase-43945.appspot.com',
    iosBundleId: 'com.example.pertemuan09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHs8Z4EhOUEcn1fr1KpNosGnISx_faY94',
    appId: '1:228705649518:web:6b304c5dd7c1d24278377f',
    messagingSenderId: '228705649518',
    projectId: 'prakflutterfirebase-43945',
    authDomain: 'prakflutterfirebase-43945.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-43945.appspot.com',
    measurementId: 'G-1SPLE1WTEB',
  );
}
